/**
 * Copyright 2016 Thomas Feng
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import static org.hamcrest.core.Is.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.Assert.assertThat;
import static play.test.Helpers.running;
import static play.test.Helpers.testServer;

import java.io.ByteArrayInputStream;
import java.math.BigInteger;
import java.util.List;
import java.util.concurrent.ExecutionException;

import org.junit.Before;
import org.junit.Test;

import akka.stream.javadsl.StreamConverters;
import controllers.protocols.Point;
import controllers.protocols.Points;
import me.tfeng.playmods.spring.ApplicationLoader;
import me.tfeng.toolbox.avro.AvroHelper;
import play.Application;
import play.ApplicationLoader.Context;
import play.Environment;
import play.libs.ws.SourceBodyWritable;
import play.libs.ws.StandaloneWSResponse;
import play.libs.ws.ahc.StandaloneAhcWSClient;

/**
 * @author Thomas Feng (huining.feng@gmail.com)
 */
public class IntegrationTest {

  private static final int PORT = 3333;

  private Application application;

  @Before
  public void setup() {
    application = new ApplicationLoader().load(new Context(Environment.simple()));
  }

  @Test
  public void testOneNearestPoint() {
    running(testServer(PORT, application), () -> {
      try {
        StandaloneAhcWSClient client = application.injector().instanceOf(StandaloneAhcWSClient.class);
        StandaloneWSResponse response;
        List<Point> nearestPoints;

        response = post(client, "/points/addPoint", "{\"point\": {\"x\": 1.0, \"y\": 2.0}}");
        assertThat(response.getStatus(), is(200));
        assertThat(response.getBody(), is("null"));

        response = post(client, "/points/addPoint", "{\"point\": {\"x\": 3.0, \"y\": 0.5}}");
        assertThat(response.getStatus(), is(200));
        assertThat(response.getBody(), is("null"));

        response = post(client, "/points/getNearestPoints", "{\"from\": {\"x\": 0.0, \"y\": 0.0}, \"k\": 1}");
        assertThat(response.getStatus(), is(200));
        nearestPoints = AvroHelper.toRecord(Points.PROTOCOL.getMessages().get("getNearestPoints").getResponse(),
            response.getBody());
        assertThat(nearestPoints.size(), is(1));
        assertThat(nearestPoints.get(0).getX(), is(1.0));
        assertThat(nearestPoints.get(0).getY(), is(2.0));
        new BigInteger(nearestPoints.get(0).getId(), 16); // Id is generated by MongoDB.
      } catch (Exception e) {
        throw new RuntimeException(e);
      }
    });
  }

  @Test
  public void testThreeNearestPoints() {
    running(testServer(PORT, application), () -> {
      try {
        StandaloneAhcWSClient client = application.injector().instanceOf(StandaloneAhcWSClient.class);
        StandaloneWSResponse response;
        List<Point> nearestPoints;

        response = post(client, "/points/addPoint", "{\"point\": {\"x\": 1.0, \"y\": 2.0}}");
        assertThat(response.getStatus(), is(200));
        assertThat(response.getBody(), is("null"));

        response = post(client, "/points/addPoint", "{\"point\": {\"x\": 3.0, \"y\": 0.5}}");
        assertThat(response.getStatus(), is(200));
        assertThat(response.getBody(), is("null"));

        response = post(client, "/points/addPoint",
            "{\"point\": {\"id\": \"53fdf8429436cecb91d26cfa\", \"x\": 2.1, \"y\": 1.8}}");
        assertThat(response.getStatus(), is(200));
        assertThat(response.getBody(), is("null"));

        response = post(client, "/points/getNearestPoints", "{\"from\": {\"x\": 0.0, \"y\": 0.0}, \"k\": 3}");
        assertThat(response.getStatus(), is(200));
        nearestPoints = AvroHelper.toRecord(Points.PROTOCOL.getMessages().get("getNearestPoints").getResponse(),
            response.getBody());
        assertThat(nearestPoints.size(), is(3));

        assertThat(nearestPoints.get(0).getX(), is(1.0));
        assertThat(nearestPoints.get(0).getY(), is(2.0));
        new BigInteger(nearestPoints.get(0).getId(), 16);

        assertThat(nearestPoints.get(1).getX(), is(2.1));
        assertThat(nearestPoints.get(1).getY(), is(1.8));
        assertThat(nearestPoints.get(1).getId(), is("53fdf8429436cecb91d26cfa"));

        assertThat(nearestPoints.get(2).getX(), is(3.0));
        assertThat(nearestPoints.get(2).getY(), is(0.5));
        new BigInteger(nearestPoints.get(2).getId(), 16);

        assertThat(new BigInteger(nearestPoints.get(0).getId(), 16),
            is(not(new BigInteger(nearestPoints.get(2).getId(), 16))));
      } catch (Exception e) {
        throw new RuntimeException(e);
      }
    });
  }

  private StandaloneWSResponse post(StandaloneAhcWSClient client, String endpoint, String data)
      throws ExecutionException, InterruptedException {
    return client.url("http://localhost:" + PORT + endpoint)
        .setContentType("avro/json")
        .post(new SourceBodyWritable(StreamConverters.fromInputStream(() -> new ByteArrayInputStream(data.getBytes()))))
        .toCompletableFuture()
        .get();
  }
}
